development:
    adapter: mysql2
    host: smyth100.local
    database: golocavore_www_dev
    username: root
    password: upandatom

test:
    adapter: mysql2
    host: smyth100.local
    database: golocavore_www_test
    username: root
    password: upandatom


production:
    adapter: mysql2
    host: localhost
    database: golocavore_www_prod
    username: root
    password: upandatom

